# Generated by Django 4.2.5 on 2025-11-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('description', models.CharField(blank=True, null=True, verbose_name='商品説明')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='価格')),
            ],
            options={
                'verbose_name_plural': '商品',
            },
        ),
    ]
